CREATE TABLE `account_book_flow_i_gm712131691323525399_54`
(
    `id`                    bigint(20) unsigned NOT NULL COMMENT '主键, 无实际意义',
    `book_trans_no`         varchar(64)         NOT NULL COMMENT '记账单号',
    `trade_no`              varchar(64)         NOT NULL COMMENT '交易单号',
    `out_order_no`          varchar(64)         NOT NULL COMMENT '外部交易单号',
    `merchant_id`           varchar(32)         NOT NULL COMMENT '商户号',
    `amount`                bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '交易金额',
    `currency`              varchar(4)          NOT NULL COMMENT '币种',
    `account_id`            varchar(64)         NOT NULL COMMENT '主体操作的用户ID',
    `account_type`          varchar(64)         NOT NULL DEFAULT '' COMMENT '账户类型',
    `pid`                   varchar(64)         NOT NULL COMMENT '主体操作的用户的账号',
    `pay_user_type`         varchar(8)          NOT NULL DEFAULT 'I' COMMENT '支付会员类型',
    `account_balance_id`    varchar(128)        NOT NULL COMMENT '主体操作的账户ID',
    `trade_type`            varchar(32)         NOT NULL COMMENT '交易类型',
    `trans_code`            varchar(128)        NOT NULL COMMENT '记账编码',
    `in_out_type`           tinyint(4)          NOT NULL DEFAULT '0' COMMENT '0（无金额变动）、1（收入）、2（支出）',
    `subject`               varchar(100)        NOT NULL COMMENT '主题',
    `after_balance`         bigint(20)          NOT NULL DEFAULT '0' COMMENT '金额变动后的余额',
    `after_pending_balance` bigint(20)          NOT NULL DEFAULT '0' COMMENT '交易的在途余额',
    `after_frozen_balance`  bigint(20)          NOT NULL DEFAULT '0' COMMENT '业务冻结余额，冻结的余额不可使用',
    `after_version`         bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '金额变动后的版本',
    `create_time`           bigint(20) unsigned NOT NULL COMMENT '创建时间',
    `complete_time`         bigint(20) unsigned          DEFAULT '0' COMMENT '完成时间',
    `state`                 tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '记账操作状态：0（初始）、1（成功）、2（冻结）、3（解冻）',
    `remark`                varchar(128)        NOT NULL COMMENT '备注',
    `accum_state`           tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '余额累加标记. 0:未累加 1:已累加',
    `accum_batch_id`        varchar(64)         NOT NULL DEFAULT '' COMMENT '余额累加批次号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_trans_no_code_account` (`book_trans_no`, `trans_code`, `account_balance_id`),
    KEY `idx_balance_id` (`account_balance_id`) COMMENT '账户ID索引',
    KEY `idx_pid` (`pid`) COMMENT 'pid建立索引',
    KEY `idx_create_time` (`create_time`) COMMENT '创建时间建立索引',
    KEY `idx_state_accum_complete` (`state`, `accum_state`, `complete_time`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='记账操作的流水表'